version: "3"
services:
  notebook:
    build: .
    platform: linux/amd64
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ..:/home/jovyan/work
    user: root
    ports:
      - 8888:8888
