version: "3"
services:
  notebook:
    build: .
    platform: linux/amd64
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - ..:/home/jovyan/work
    user: root
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token=''
