version: '3.8'
services:
  notebook:
    build: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    volumes:
      - ./src:/home/jovyan/work
    user: root
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.token=''
